Merge
threefoldtech/jumpscale_core pull request #163
Opened 2018-12-11 11:02 UTC by rkhamis

Merging development into development_960

2018-12-11 11:04 UTC, xmonader commented on .travis.yml
>  dist: trusty
is that the latest one? I thought jumpscale is going for 18.04 no?

2018-12-11 11:04 UTC, rkhamis commented on .travis.yml
>  dist: trusty
true dat! nice catch, yo

2018-12-11 11:07 UTC, rkhamis commented on .travis.yml
>  dist: trusty
seems like it's not yet supported by travis. Guess all the tests will fail immediately

2018-12-11 11:43 UTC, zaibon commented on .travis.yml
>  dist: trusty
This Travis doesnt have that version indeed. That's why the test script build a docker images of Ubuntu 18.04 and run the test inside

2018-12-11 11:44 UTC, zaibon commented on .travis.yml
>  dist: trusty
Woops miss clicked to resolved... Sorry

2018-12-11 12:14 UTC, zaibon requested changes
Need to review the templates files to make sure the autoformatting didn't screw them up.

Also during such a big PR. Mixing merge and auto formatting make it nearly impossible to review. Next time make a commit for the merge and one for the formatting.

2018-12-11 12:14 UTC, zaibon commented on .travis.yml
>  dist: trusty
Woops miss clicked on resolved...
also I see the we don't use docker for the test. So yeah well have to check how to solve this. Maybe Juste using python 3.6 is enough

2018-12-11 12:14 UTC, zaibon commented on cmds/js9
> +js_shell
This file can probably be removed

2018-12-13 07:35 UTC, zaibon requested changes
Can we also remove the filtering of travis on the branches ?
I want to have travis running test for any branches

2019-05-28 06:38 UTC, closed without merging